src/radio/api/urls.py
from django.conf.urls import url

from .views import (
    RadioPlayAPIView, PlayerCommandAPIView, RadioListAPIView,
    PlayerStatusAPIView, MP3PlaylistAPIView
)

urlpatterns = [
    url(r'^player/status/$', PlayerStatusAPIView.as_view(), name='status'),
    url(r'^player/command/$', PlayerCommandAPIView.as_view(), name='command'),
    url(r'^player/playlist/$', MP3PlaylistAPIView.as_view(), name='playlist'),

    url(r'^radios/$', RadioListAPIView.as_view(), name='radio_list'),
    url(r'^radios/(?P<pk>[\w-]+)/$', RadioPlayAPIView.as_view(), name='play'),
]

src/radio/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.views.generic import RedirectView

from .api.urls import urlpatterns as api_urls
from .frontend.views import HomeView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_urls, namespace='api')),
    url(r'home/', HomeView.as_view(), name='home'),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('home'))),
]

src/radio/entities/models.py
from django.db import models


class Station(models.Model):
    name = models.CharField(max_length=200)

    url = models.URLField(max_length=512, blank=False,
                          verbose_name="Playable URL of the radio stream")

    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

src/radio/frontend/forms/youtube.py
from django import forms


class YoutubeForm(forms.Form):
    youtube_url = forms.CharField(
        widget=forms.TextInput(attrs={'size': 100, 'class': 'col-xs-12'}),
        max_length=512,
    )

src/radio/api/views.py
import logging
from collections import OrderedDict

from django.shortcuts import get_object_or_404

from rest_framework.response import Response
from rest_framework.generics import ListAPIView, RetrieveAPIView

from .utils import send_command
from ..entities.models import Station

logger = logging.getLogger(__name__)


class PlayerStatusAPIView(RetrieveAPIView):
    def get(self, request, **kwargs):
        response = send_command("mpc").split('\n')[:-1]
        try:
            response[-1] = response[-1].split(' repeat')[0]
        except IndexError:
            pass
        return Response(" :: ".join(response))


class PlayerCommandAPIView(RetrieveAPIView):
    def get(self, request, **kwargs):
        if len(request.query_params) > 1:
            first = request.query_params.get('first')
            second = request.query_params.get('second')
            query_params = [x for x in (first, second) if x]
        else:
            query_params = list(request.query_params)
        response = send_command('mpc', *query_params).split('\n')[:-1]
        try:
            response[-1] = response[-1].split(' repeat')[0]
        except IndexError:
            pass
        logger.info('Sent: mpc {}. Response: {}'.format(query_params, response))
        return Response(" :: ".join(response))


class RadioListAPIView(ListAPIView):
    def get(self, request, **kwargs):
        station_list = Station.objects.all()
        response = OrderedDict()
        response['Number of stations'] = len(station_list)
        response['stations'] = OrderedDict()
        for station in station_list:
            response['stations'][station.name] = station.url
        return Response(response)


class RadioPlayAPIView(RetrieveAPIView):
    @staticmethod
    def play_single_file(file):
        send_command('mpc', 'clear')
        send_command('mpc', 'add', file)
        send_command('mpc', 'add', file)
        send_command('mpc', 'play')

    def get(self, request, **kwargs):
        station = get_object_or_404(Station, pk=kwargs.get('pk'))
        self.play_single_file(station.url)
        return Response('Playing {}'.format(station.name))


class MP3PlaylistAPIView(RetrieveAPIView):
    def get(self, request, **kwargs):
        send_command('mpc', 'clear')
        all_music = send_command('mpc', 'listall').split('\n')[:-1]
        for song in all_music:
            send_command('mpc', 'add', song)
        return Response(send_command('mpc', 'playlist').split('\n'))

src/radio/frontend/views.py
import subprocess
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from rest_framework.reverse import reverse
from django.views.generic import ListView

from radio.entities.models import Station
from radio.frontend.forms.youtube import YoutubeForm


class HomeView(ListView):
    model = Station
    template_name = "index.html"

    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            return super().get(request, **kwargs)
        return HttpResponse(
            status=401,
            content='<div>Unauthenticated!</div>'
                    '<div>Click <a href={}> here </a> to login</div>'.format(
                request.build_absolute_uri('/admin/login/?next={}'.format(
                    request.get_full_path()
                ))
            ))
    @staticmethod
    def find_between(s, first, last):
        try:
            start = s.index(first) + len(first)
            end = s.index(last, start)
            return s[start:end]
        except ValueError:
            return ""

    @staticmethod
    def system_do(args, split=True):
        if split:
            args = args.split(' ')
        process = subprocess.Popen(args, stdout=subprocess.PIPE)
        return process.communicate()[0]

    def get_context_data(self, **kwargs):
        form = YoutubeForm()
        context = super().get_context_data()
        context['form'] = form
        return context

    def post(self, request, **kwargs):
        form = YoutubeForm(data=request.POST)
        if form.is_valid():
            url = form.data['youtube_url']

            out, err, *junk = self.system_do(
                "youtube-dl {} -x --audio-format mp3".format(url))
            filename = self.find_between(str(out), 'Destination:', '.mp3')
            try:
                filename = filename[filename.index('Destination:')+13:]
            except ValueError:
                print(filename)
                pass
            print("filename: {}.mp3".format(filename))
            self.system_do(
                ["sudo", "mv", "{}.mp3".format(filename), "/mnt/music"], split=False
            )
            print('moved to /mnt/music')
            self.system_do("mpc clear")
            self.system_do("mpc update")
            self.system_do(
                ["mpc", "add", "music/{}.mp3".format(filename)], split=False)
            self.system_do("mpc play")
            print('Playing')

        return HttpResponseRedirect(reverse('home'))

src/radio/frontend/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author"      content="Sergey Pozhilov (GetTemplate.com)">
	
	<title>Raspberry Media Player</title>

	<link rel="shortcut icon" href="{% static "images/gt_favicon.png"%}">
	<!-- Bootstrap itself -->
	<link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" type="text/css">

	<!-- Custom styles -->
	<link rel="stylesheet" href="{% static "css/magister.css"%}">

	<!-- Fonts -->
	<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href='http://fonts.googleapis.com/css?family=Wire+One' rel='stylesheet' type='text/css'>
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script>
        function add_button (parent, text, index) {
            var buttonElement = document.createElement("button");
            var classAtt = document.createAttribute("class");
            classAtt .value = "btn btn-default";
            var onclickAtt = document.createAttribute("onclick");
            onclickAtt.value = "call_api('{% url 'api:command' %}?first=play&second=" + index + "', 'GET');";
            buttonElement.setAttributeNode(classAtt);
            buttonElement.setAttributeNode(onclickAtt);

            var textNode = document.createTextNode(text);
            buttonElement.appendChild(textNode);

            var divElement = document.createElement("div");
            var rowClass = document.createAttribute("class");
            rowClass.value = "row";
            divElement.setAttributeNode(rowClass);
            divElement.appendChild(buttonElement);
            parent.appendChild(divElement);
        }
        function call_api(url, method, element_id, populate_playlist) {
            if (method == null) {
                method = 'GET'
            }
            if (element_id == null) {
                element_id = '#player_status'
            }

            var xmlHttp = new XMLHttpRequest();
            xmlHttp.onreadystatechange = function () {
                if (xmlHttp.readyState == XMLHttpRequest.DONE) {
                    if (populate_playlist != null) {
                        var playlistElement = document.getElementById(element_id);
                        while (playlistElement.hasChildNodes()) {
                            playlistElement.removeChild(playlistElement.firstChild)
                        }
                        var array = xmlHttp.responseText.split('","');
                        var first_element = array[0].slice(2);

                        add_button(playlistElement, first_element, 1);
                        for (var i=1; i<array.length-1; i++) {
                            add_button(playlistElement, array[i], i+1);
                        }

                    } else {
                        $(element_id).text(xmlHttp.responseText);
                    }
                }
            };
            xmlHttp.open(method, url, true); // true for asynchronous
            xmlHttp.send(null);
        }

{#        get_status();#}
{#        setInterval(get_status, 10*1000);#}

    </script>
</head>

<!-- use "theme-invert" class on bright backgrounds, also try "text-shadows" class -->
<body class="theme-invert">

<div class="text-center" style="position: fixed; width: 100%;">

    <div class="label-custom" style="padding-top: 60px;">Player Information</div>
    <div class="label-custom" id="player_status"> </div>
</div>
<div class="text-right" style="position: relative">
    <div class="row"> Hello
        {{ request.user.username }}
        <a href="{% url 'admin:logout' %}">Logout</a>
    </div>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-center">
            <button class="btn btn-default" onclick="call_api('{% url 'api:command' %}?prev');">
                <i class="glyphicon glyphicon-step-backward"></i>
            </button>
            <button class="btn btn-success" onclick="call_api('{% url 'api:command' %}?play');">
                <i class="glyphicon glyphicon-play"></i>
            </button>
            <button class="btn btn-default" onclick="call_api('{% url 'api:command' %}?pause');">
                <i class="glyphicon glyphicon-pause"></i>
            </button>
            <button class="btn btn-danger" onclick="call_api('{% url 'api:command' %}?stop');">
                <i class="glyphicon glyphicon-stop"></i>
            </button>
            <button class="btn btn-default" onclick="call_api('{% url 'api:command' %}?next');">
                <i class="glyphicon glyphicon-step-forward"></i>
            </button>
            <button type="button" class="btn btn-info" onclick="call_api('{% url 'api:command' %}?first=volume&second=%2D5');">
                <i class="glyphicon glyphicon-volume-down"></i>
            </button>
            <button type="button" class="btn btn-info" onclick="call_api('{% url 'api:command' %}?first=volume&second=%2B5');">
                <i class="glyphicon glyphicon-volume-up"></i>
            </button>
            <button type="button" class="btn btn-default" onclick="call_api('{% url 'api:status' %}');">
                <i class="glyphicon glyphicon-refresh"></i>
                Player Info
            </button>
        </div>
    </div>
</div>


<nav class="mainmenu">
	<div class="container">
		<div class="dropdown">
			<button type="button" class="navbar-toggle" data-toggle="dropdown"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
			<!-- <a data-toggle="dropdown" href="#">Dropdown trigger</a> -->
			<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
				<li><a href="#home" class="active">Home</a></li>
				<li><a href="#radio">Radio</a></li>
				<li><a href="#youtube">Youtube</a></li>
			</ul>
		</div>
	</div>
</nav>

<!-- Main (Home) section -->
<section class="section" id="home">
	<div class="container">

		<div class="row">
			<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">	

				<!-- Site Title, your name, HELLO msg, etc. -->
				<h1 class="title">Raspberry Media Player</h1>

				<!-- Short introductory (optional) -->
				<h5 class="tagline">
					Use the upper-left menu to navigate between player types<br>
					MP3 Player (Home) | Radio | YouTube Download & Play
				</h5>


                <br><br><br>
                <button class="btn btn-primary" onclick="call_api('{% url 'api:playlist' %}', 'GET', 'playlist', 'True');">
                    Refresh playlist <i class="glyphicon glyphicon-refresh"></i>
                </button>
                <br><br><br>
                <div class="list-group" id="playlist">
                </div>
			</div> <!-- /col -->
		</div> <!-- /row -->

	</div>
</section>

<!-- Second (About) section -->
<section class="section" id="radio">
	<div class="container">
        <h2 class="text-center title">Radio Playlist</h2>
        <p class="lead text-center">
			Just click on the radio you want to hear
		</p>
        {% for object in object_list %}
            <div class="row text-center">
                <button class="btn btn-primary" onclick="call_api('{% url 'api:play' pk=object.pk %}');">
                    {{ object.name }}
                </button>
            </div>
            <br>
        {% endfor %}
	</div>
</section>

<!-- Third (Youtube) section -->
<section class="section" id="youtube">
	<div class="container">
		<h2 class="text-center title">Youtube</h2>
		<div class="row">
			<div class="col-xs-12 text-center">
				<p>Input your favorite youtube url and that song will be downloaded,</p>
				<p>saved into your mp3 playlist and played<br><br></p>
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <br><br>
                    <button type="submit" class="btn btn-danger col-xs-12">Save & Play</button>
                </form>
			</div>
		</div>
	</div>
</section>
<!-- Load js libs only when the page is loaded. -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<script src="{% static "js/modernizr.custom.72241.js" %}"></script>
<!-- Custom template scripts -->
<script src="{% static "js/magister.js" %}"></script>
</body>
</html>